name: PR Checks

on:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: latest
      - name: Sync Dependencies
        run: cd backend && make sync

  black:
    name: Run Black (Formatting)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Black
        run: cd backend && make format_check

  mypy:
    name: Run MyPy (Type Checking)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run MyPy
        run: cd backend && make mypy

  flake8:
    name: Run Flake8 (Linting)
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Flake8
        run: cd backend && make flake8